# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dispatcher.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(971, 887)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.regionGroup = QtWidgets.QGroupBox(self.centralwidget)
        self.regionGroup.setGeometry(QtCore.QRect(700, 10, 261, 241))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.regionGroup.setFont(font)
        self.regionGroup.setAutoFillBackground(False)
        self.regionGroup.setAlignment(QtCore.Qt.AlignCenter)
        self.regionGroup.setFlat(False)
        self.regionGroup.setObjectName("regionGroup")
        self.gridLayoutWidget = QtWidgets.QWidget(self.regionGroup)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 20, 261, 221))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 6)
        self.gridLayout.setObjectName("gridLayout")
        self.filterList = QtWidgets.QListWidget(self.gridLayoutWidget)
        self.filterList.setAutoFillBackground(True)
        self.filterList.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.filterList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.filterList.setProperty("showDropIndicator", False)
        self.filterList.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.filterList.setAlternatingRowColors(True)
        self.filterList.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.filterList.setWordWrap(True)
        self.filterList.setObjectName("filterList")
        item = QtWidgets.QListWidgetItem()
        self.filterList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.filterList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.filterList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.filterList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.filterList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.filterList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.filterList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.filterList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.filterList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.filterList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.filterList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.filterList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.filterList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.filterList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.filterList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.filterList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.filterList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.filterList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.filterList.addItem(item)
        self.gridLayout.addWidget(self.filterList, 0, 1, 1, 1)
        self.applyFilterBox = QtWidgets.QDialogButtonBox(self.gridLayoutWidget)
        self.applyFilterBox.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Reset)
        self.applyFilterBox.setObjectName("applyFilterBox")
        self.gridLayout.addWidget(self.applyFilterBox, 1, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.searchGroup = QtWidgets.QGroupBox(self.centralwidget)
        self.searchGroup.setGeometry(QtCore.QRect(10, 10, 681, 241))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        self.searchGroup.setFont(font)
        self.searchGroup.setObjectName("searchGroup")
        self.formLayoutWidget = QtWidgets.QWidget(self.searchGroup)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 20, 400, 221))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setMinimumSize(QtCore.QSize(120, 0))
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.depFilter = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.depFilter.setMaximumSize(QtCore.QSize(55, 16777215))
        self.depFilter.setText("")
        self.depFilter.setObjectName("depFilter")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.depFilter)
        self.depCalendar = QtWidgets.QCalendarWidget(self.formLayoutWidget)
        self.depCalendar.setObjectName("depCalendar")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.depCalendar)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.depTime = QtWidgets.QComboBox(self.formLayoutWidget)
        self.depTime.setObjectName("depTime")
        self.depTime.addItem("")
        self.depTime.addItem("")
        self.depTime.addItem("")
        self.depTime.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.depTime)
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.searchGroup)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(410, 20, 271, 101))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.arrFilter = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.arrFilter.setMaximumSize(QtCore.QSize(55, 16777215))
        self.arrFilter.setText("")
        self.arrFilter.setObjectName("arrFilter")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.arrFilter)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.airlineFilter = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.airlineFilter.setMaxVisibleItems(15)
        self.airlineFilter.setObjectName("airlineFilter")
        self.airlineFilter.addItem("")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.airlineFilter)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.aircraftFilter = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.aircraftFilter.setObjectName("aircraftFilter")
        self.aircraftFilter.addItem("")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.aircraftFilter)
        self.searchButton = QtWidgets.QPushButton(self.searchGroup)
        self.searchButton.setGeometry(QtCore.QRect(410, 140, 131, 91))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.searchButton.setFont(font)
        self.searchButton.setCheckable(False)
        self.searchButton.setObjectName("searchButton")
        self.resetButton = QtWidgets.QPushButton(self.searchGroup)
        self.resetButton.setGeometry(QtCore.QRect(550, 140, 121, 91))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.resetButton.setFont(font)
        self.resetButton.setObjectName("resetButton")
        self.resultGroup = QtWidgets.QGroupBox(self.centralwidget)
        self.resultGroup.setGeometry(QtCore.QRect(10, 260, 951, 471))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        self.resultGroup.setFont(font)
        self.resultGroup.setObjectName("resultGroup")
        self.tableView = QtWidgets.QTableView(self.resultGroup)
        self.tableView.setGeometry(QtCore.QRect(10, 30, 931, 431))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        self.tableView.setFont(font)
        self.tableView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableView.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableView.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        self.tableView.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView.setTabKeyNavigation(False)
        self.tableView.setProperty("showDropIndicator", False)
        self.tableView.setDragDropOverwriteMode(False)
        self.tableView.setAlternatingRowColors(True)
        self.tableView.setGridStyle(QtCore.Qt.SolidLine)
        self.tableView.setObjectName("tableView")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 971, 20))
        self.menubar.setObjectName("menubar")
        self.menuData = QtWidgets.QMenu(self.menubar)
        self.menuData.setObjectName("menuData")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionE_xit = QtWidgets.QAction(MainWindow)
        self.actionE_xit.setObjectName("actionE_xit")
        self.menuData.addAction(self.actionOpen)
        self.menuHelp.addAction(self.actionAbout)
        self.menu_File.addAction(self.actionE_xit)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menuData.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DispatcherX"))
        self.regionGroup.setTitle(_translate("MainWindow", "Filter by region"))
        __sortingEnabled = self.filterList.isSortingEnabled()
        self.filterList.setSortingEnabled(False)
        item = self.filterList.item(0)
        item.setText(_translate("MainWindow", "K - United States (mainland)"))
        item = self.filterList.item(1)
        item.setText(_translate("MainWindow", "E - Northern Europe / Scandinavia"))
        item = self.filterList.item(2)
        item.setText(_translate("MainWindow", "L - Southern Europe"))
        item = self.filterList.item(3)
        item.setText(_translate("MainWindow", "C - Canada"))
        item = self.filterList.item(4)
        item.setText(_translate("MainWindow", "M - Central America"))
        item = self.filterList.item(5)
        item.setText(_translate("MainWindow", "T - Caribbean"))
        item = self.filterList.item(6)
        item.setText(_translate("MainWindow", "S - South America"))
        item = self.filterList.item(7)
        item.setText(_translate("MainWindow", "O - The Middle East"))
        item = self.filterList.item(8)
        item.setText(_translate("MainWindow", "V - India and Southeast Asia"))
        item = self.filterList.item(9)
        item.setText(_translate("MainWindow", "W - Indonesia, Singapore, Phillippines"))
        item = self.filterList.item(10)
        item.setText(_translate("MainWindow", "G/D/H/F - Africa"))
        item = self.filterList.item(11)
        item.setText(_translate("MainWindow", "B - Greenland/Iceland/Kosovo"))
        item = self.filterList.item(12)
        item.setText(_translate("MainWindow", "U - Russia and Former Soviet Republics"))
        item = self.filterList.item(13)
        item.setText(_translate("MainWindow", "Z - China"))
        item = self.filterList.item(14)
        item.setText(_translate("MainWindow", "R - Japan, Taiwan, and Korea"))
        item = self.filterList.item(15)
        item.setText(_translate("MainWindow", "Y - Australia"))
        item = self.filterList.item(16)
        item.setText(_translate("MainWindow", "N - New Zealand and the South Pacific"))
        item = self.filterList.item(17)
        item.setText(_translate("MainWindow", "A - Solomon Islands, Papa New Guinea, Nauru"))
        item = self.filterList.item(18)
        item.setText(_translate("MainWindow", "P - Alaska, Hawaii, and North Pacific Territories"))
        self.filterList.setSortingEnabled(__sortingEnabled)
        self.searchGroup.setTitle(_translate("MainWindow", "Define your flight parameters:"))
        self.label.setText(_translate("MainWindow", "Departure Airport:"))
        self.label_2.setText(_translate("MainWindow", "Departure date:"))
        self.label_5.setText(_translate("MainWindow", "Departure time"))
        self.depTime.setItemText(0, _translate("MainWindow", "Any"))
        self.depTime.setItemText(1, _translate("MainWindow", "Morning (0400 - 1200)"))
        self.depTime.setItemText(2, _translate("MainWindow", "Afternoon (1200 - 2000)"))
        self.depTime.setItemText(3, _translate("MainWindow", "Night (2000 - 0400)"))
        self.label_3.setText(_translate("MainWindow", "Arrival Airport:"))
        self.label_6.setText(_translate("MainWindow", "Airline"))
        self.airlineFilter.setItemText(0, _translate("MainWindow", "Any"))
        self.label_4.setText(_translate("MainWindow", "Aircraft:"))
        self.aircraftFilter.setItemText(0, _translate("MainWindow", "Any"))
        self.searchButton.setText(_translate("MainWindow", "&Search"))
        self.resetButton.setText(_translate("MainWindow", "&Reset"))
        self.resultGroup.setTitle(_translate("MainWindow", "Results:"))
        self.menuData.setTitle(_translate("MainWindow", "&Data"))
        self.menuHelp.setTitle(_translate("MainWindow", "&Help"))
        self.menu_File.setTitle(_translate("MainWindow", "&File"))
        self.actionOpen.setText(_translate("MainWindow", "&Open"))
        self.actionOpen.setStatusTip(_translate("MainWindow", "Open a database of saved flights in RFD format"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionAbout.setText(_translate("MainWindow", "&About"))
        self.actionE_xit.setText(_translate("MainWindow", "E&xit"))
        self.actionE_xit.setStatusTip(_translate("MainWindow", "Quit DispatcherX"))
